spring.application.name=game

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/sideproject_game
spring.datasource.username=sideproject
spring.datasource.password=sideproject1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.initialization-fail-timeout=0

logging.level.org.hibernate.SQL=debug
