spring.application.name=game

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/sideproject_game
spring.datasource.username=sideproject
spring.datasource.password=sideproject1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=debug
